django_nyt/urls.py
from django import VERSION as DJANGO_VERSION
from django.conf.urls import include, url

from . import views

app_name = 'nyt'

urlpatterns = [
    url('^json/get/$', views.get_notifications, name='json_get'),
    url('^json/get/(?P<latest_id>\d+)/$', views.get_notifications, name='json_get'),
    url('^json/mark-read/$', views.mark_read, name='json_mark_read_base'),
    url('^json/mark-read/(\d+)/$', views.mark_read, name='json_mark_read'),
    url('^json/mark-read/(?P<id_lte>\d+)/(?P<id_gte>\d+)/$', views.mark_read, name='json_mark_read'),
    url('^goto/(?P<notification_id>\d+)/$', views.goto, name='goto'),
    url('^goto/$', views.goto, name='goto_base'),
]


def get_pattern(app_name=app_name, namespace="nyt"):
    """Every url resolution takes place as "nyt:view_name".
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    import warnings
    warnings.warn(
        'django_nyt.urls.get_pattern is deprecated and will be removed in next version,'
        ' just use include(\'django_nyt.urls\')', DeprecationWarning
    )
    return include('django_nyt.urls')

iimt4601/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wingwoo.urls')),
    path('notifications/', include('django_nyt.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

wingwoo/urls.py
from django.urls import path, re_path
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    #registration
    path('register/', views.process_register , name='register'),
    path('login/', views.process_login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),

    #navigation
    path('about/',views.about, name='about'),
    path('products/',views.products, name='products'),
    path('products/<str:category>/', views.product_detail, name="product_detail"),
    path('contact/',views.contact, name='contact'),

    #Form
    path('generalpurchaseorder/<str:category>/',views.generalPurchaseOrderForm, name="generalpurchaseorder"),
    path('carpetpurchaseorder/',views.carpetPurchaseOrderForm, name="carpetpurchaseorder"),
    path('repairorder/<str:category>/',views.repairOrderForm, name="repairorder"),
    path('boat/', views.boat, name="boat"),
    path('remove_boat/', views.remove_boat, name="remove_boat"),
    path('edit_boat', views.edit_boat, name='edit_boat'),
    path('get_boat', views.get_boat, name='get_boat'),
    path('getform/', views.get_form, name='getform'),

    #Other methods
    path('orders/', views.orders, name='orders'),
    path('vieworders/<int:is_paid>/<int:is_purchase>/', views.vieworders, name='vieworders'),
    path('timeslotok/', views.is_datetime_available, name='timeslotok'),
    path('schedule/', views.schedule, name='schedule'),
    path('timeslotdetail/', views.get_timeslot_detail, name='timeslotdetail'),
    path('getorderoptions/', views.get_order_options, name='getorderoptions'),
    path('quoteorder/', views.quote_order, name='quoteorder'),
    path('madeorder/', views.made_order, name='madeorder'),
    path('receivedpayment/', views.received_payment, name='receivedpayment'),
    path('deliveredorder/', views.delivered_order, name='deliveredorder'),
    path('reverseorderstatus/', views.reverse_order, name='reverseorder'),
    path('finishedbooking/', views.finished_booking, name='finishedbooking'),

    path('getpricedetail/', views.get_price_detail, name='getpricedetail'),
    path('createbooking/', views.create_booking, name='createbooking'),
    path('removeupload/', views.remove_upload, name='removeupload'),
    
    path('editrepairorder/', views.edit_repair_order, name='editrepairorder'),
    path('editgeneralpurchaseorder/', views.edit_general_purchase_order, name='editgeneralpurchaseorder'),
    path('editcarpetpurchaseorder/', views.edit_carpet_purchase_order, name='editcarpetpurchaseorder'),
    
    path('candeleteorder/', views.can_delete_order, name="candeleteorder"),
    path('deleteorder/',views.delete_order, name="deleteorder"),
    
    path('password/', views.change_password, name='change_password'),
    path('password_reset/', auth_views.password_reset, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    re_path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),

    path('viewbookings/', views.view_bookings, name='view_bookings'),

    path('viewprofile/', views.view_profile, name='view_profile'),

    path('candeletebooking/', views.can_delete_booking, name="candeletebooking"),
    path('deletebooking/',views.delete_booking, name="deletebooking"),
    path('editbooking/', views.edit_booking, name="editbooking"),

    path('adminorders/<int:status>/', views.admin_orders, name="adminorders"),
    path('createreceivable/', views.create_receivable, name="createreceivable"),

    path('admin/memberlog/', views.admin_member_log, name="memberlog"),
    path('admin/memberlog/get/', views.admin_get_membet_log, name="getmemberlog"),
    path('admin/memberlog/export/', views.export_member_log, name="exportmemberlog"),
    path('admin/memberlog/export/<int:member_id>', views.export_member_log_id, name="exportmemberlogid"),
    path('admin/memberlog/export/<str:member_name>', views.export_member_log_name, name="exportmemberlogname"),

    path('admin/contactmessage/', views.admin_contact_message, name="contactmessage"),
    path('admin/getcontactmessages/<int:read>/', views.get_contact_message, name="getcontactmessage"),
    path('admin/readcontactmessage/', views.read_contact_message, name="readcontactmessage"),
    path('admin/unreadcontactmessage/', views.unread_contact_message, name="unreadcontactmessage"),
    path('admin/deletecontactmessage/', views.delete_contact_message, name="deletecontactmessage"),
]

"""path('products/cover/' ,views.cover, name='cover'),
    path('products/top/' ,views.top, name='top'),
    path('products/cushion/' ,views.cushion, name='cushion'),"""

wingwoo/models.py
import datetime
from decimal import *
from django.db import models, transaction
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.urls import reverse
from django.core.files import File
from templated_email import send_templated_mail, InlineImage
from .choices import *
from .utils import *
import threading
import os

from django_nyt.utils import notify

from abc import ABCMeta, abstractmethod

# Create your models here.
class Member(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=50, null=True, blank=True)
	phone = models.CharField(max_length=15, null=True, blank=True)

	def get_display_name(self):
		return str(self.name)

	def __str__(self):
		return self.get_display_name()

# @receiver(post_save, sender=User)
# def update_user_member(sender, instance, created, **kwargs):
#     if created:
#         Member.objects.create(user=instance)
#     instance.member.save()

class Address(models.Model):
	district = models.IntegerField(choices=ADDRESS_DISTRICT_CHOICES, default=ADDRESS_DISTRICT_SAIKUNG)
	pier = models.CharField(max_length=200)

	def get_detail(self):
		detail = {
			'district': self.district,
			'pier': self.pier
		}

		return detail

	def get_str(self):
		return '[' + self.get_district_display() + '] ' + self.pier

	def __str__(self):
		return self.get_str()

class Boat(models.Model):
	member = models.ForeignKey(Member, on_delete=models.CASCADE)
	address = models.ForeignKey(Address, on_delete=models.CASCADE)
	model = models.CharField(max_length=80)
	num_related_booking = models.IntegerField(default=0)
	locked = models.BooleanField(default=False)
	removed = models.BooleanField(default=False)

	@classmethod
	def create(cls, member, address, model):
		boat = cls(
			member = member, 
			address = address, 
			model = model,
			locked = False,
			num_related_booking = 0
		)
		boat.save()

		MemberLog.create(member, 'Added a new boat')

		return boat

	def get_detail(self, for_admin):
		detail = {
			'id': self.id,
			'model': self.model
		}

		if for_admin:
			detail['address'] = self.address.get_detail()
		else:
			detail['district'] = self.address.district

		return detail

	def edit(self, address, model):
		if self.num_related_booking > 0:
			raise Exception('Boat cannot be edited when it is related to a scheduled measurement booking')

		self.address = address
		self.model = model
		self.save()
		MemberLog.create(self.member, 'Edited boat#' + str(self.id) + ' ' + str(self.model))

	def remove(self):
		if self.num_related_booking > 0:
			raise Exception('Boat cannot be removed when it is related to a scheduled measurement booking')
		
		if Order.objects.filter(boat = self).count() > 0:
			self.removed = True
			self.save()
		else:
			self.delete()

		MemberLog.create(self.member, 'Removed boat#' + str(self.id) + ' ' + str(self.model))

	def get_address_display(self):
		return self.address.get_str()

	def increase_num_related_booking(self):
		self.num_related_booking += 1
		self.save()

	def decrease_num_related_booking(self):
		self.num_related_booking -= 1
		self.save()

	def __str__(self):
		return self.member.get_display_name() + '\'s ' + self.model

class ProductFeature(models.Model):
	description = models.CharField(max_length=100)

	def __str__(self):
		return self.description

class Product(models.Model):
	product_type = models.IntegerField(choices=PRODUCT_TYPE_CHOICES, default=PRODUCT_TYPE_GENERAL)
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=300, null=True, blank=True)
	feature = models.ManyToManyField(ProductFeature, through='ProductFeatureLine')
	area_calculation = models.BooleanField(default=True)
	purchase_unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

	def get_dimension(self, length, width, height):
		if self.area_calculation == True:
			dimension = get_max_area(length, width, height)
		else:
			dimension = get_max_length(length, width, height)
		return dimension

	def get_price(self, size, color, pattern, waterproof, underlay, edge):
		if self.product_type == PRODUCT_TYPE_GENERAL:
			return GeneralProduct.objects.get(id = self.id).get_price(size)
		else:
			return CarpetProduct.objects.get(id = self.id).get_price(size, pattern, waterproof, underlay, edge)

	def get_price_detail(self, length, width, height, pattern, waterproof, underlay, edge, quantity):
		if self.product_type == PRODUCT_TYPE_GENERAL:
			return GeneralProduct.objects.get(id = self.id).get_price_detail(length, width, height, quantity)
		else:
			return CarpetProduct.objects.get(id = self.id).get_price_detail(length, width, height, pattern, waterproof, underlay, edge, quantity)

	def __str__(self):
		return self.name

class GeneralProduct(Product):
	purchase_unit_price_for_color = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

	def get_price_base(self, length, width, height):
		dimension = self.get_dimension(length, width, height)

		unit_price = self.purchase_unit_price + self.purchase_unit_price_for_color

		return dimension * unit_price

	def get_price(self, size):
		return self.get_price_base(size.length, size.width, size.height)

	def get_price_detail(self, length, width, height, quantity):
		detail = {
			'purchase_unit_price': self.purchase_unit_price,
			'purchase_unit_price_for_color': self.purchase_unit_price_for_color,
			'dimension': self.get_dimension(length, width, height),
			'total_unit_price': self.get_price_base(length, width, height),
			'quantity': quantity
		}

		return detail

class CarpetProduct(Product):
	shaggy_pattern_purchase_unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
	pile_pattern_purchase_unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
	waterproof_purchase_unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
	underlay_purchase_unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
	edge_purchase_unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

	def get_pattern_price(self, pattern, length, width, height):
		area = get_max_area(length, width, height)
		if pattern.pattern_type == CARPET_TYPE_SHAGGY:
			return self.shaggy_pattern_purchase_unit_price * area
		else:
			return self.pile_pattern_purchase_unit_price * area

	def get_waterproof_price(self, waterproof, length, width, height):
		if waterproof == True:
			return self.waterproof_purchase_unit_price * get_max_area(length, width, height)
		else:
			return Decimal(0.0)

	def get_underlay_price(self, underlay, length, width, height):
		if underlay == True:
			return self.underlay_purchase_unit_price * get_max_area(length, width, height)
		else:
			return Decimal(0.0)

	def get_edge_price(self, edge, length, width, height):
		if edge == True:
			return self.edge_purchase_unit_price * get_max_perimeter(length, width, height)
		else:
			return Decimal(0.0)

	def get_price_base(self, length, width, height, pattern, waterproof, underlay, edge):
		area = get_max_area(length, width, height)

		add_on_price = self.get_pattern_price(pattern, length, width, height)
		add_on_price = add_on_price + self.get_waterproof_price(waterproof, length, width, height)
		add_on_price = add_on_price + self.get_underlay_price(underlay, length, width, height)
		add_on_price = add_on_price + self.get_edge_price(edge, length, width, height)

		return area * self.purchase_unit_price + add_on_price

	def get_price(self, size, pattern, waterproof, underlay, edge):
		return self.get_price_base(size.length, size.width, size.height, pattern, waterproof, underlay, edge)

	def get_price_detail(self, length, width, height, pattern, waterproof, underlay, edge, quantity):
		detail = {
			'dimension': self.get_dimension(length, width, height),
			'purchase_unit_price': self.purchase_unit_price,

			'pattern_price': self.get_pattern_price(pattern, length, width, height),

			'waterproof_unit_price': self.waterproof_purchase_unit_price,
			'waterproof_price': self.get_waterproof_price(waterproof, length, width, height),

			'underlay_unit_price': self.underlay_purchase_unit_price,
			'underlay_price': self.get_underlay_price(underlay, length, width, height),

			'edge_unit_price': self.edge_purchase_unit_price,
			'edge_price': self.get_edge_price(edge, length, width, height),

			'total_unit_price': self.get_price_base(length, width, height, pattern, waterproof, underlay, edge),
			'quantity': quantity
		}

		if pattern.pattern_type == CARPET_TYPE_SHAGGY:
			detail['pattern_unit_price'] = self.shaggy_pattern_purchase_unit_price
		else:
			detail['pattern_unit_price'] = self.pile_pattern_purchase_unit_price

		return detail

class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
	image = models.ImageField(upload_to='image/product/')

class ProductFeatureLine(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	product_feature = models.ForeignKey(ProductFeature, on_delete=models.CASCADE)

	def __str__(self):
		return self.product.name + ": " + self.product_feature.description

class Color(models.Model):
	code = models.CharField(max_length=50)
	name = models.CharField(max_length=50)
	image = models.ImageField(upload_to='image/color/')

	def get_detail(self):
		detail = {
			'id': self.id,
			'code': self.code,
			'name': self.name,
			'image': static(self.image.url)
		}

		return detail

	def __str__(self):
		return self.code + " " + self.name

class CarpetPattern(models.Model):
	code = models.CharField(max_length=50)
	name = models.CharField(max_length=50)

wingwoo/templates/forms/CarpetPurchaseOrder.html
{% extends 'forms/PurchaseOrder.html' %}

{% load widget_tweaks %}

{% block colorpattern %}
<div class="real-form-group">
	{% with field=form.pattern %}
		{{ field.label_tag }}
		<div class="form-inline">
		{% if form.is_bound %}
			  {% if field.errors %}
				  {% include "wingwoo/field_pattern.html" with class="form-control is-invalid" field=field %}
				{% for error in field.errors %}
				<div class="invalid-feedback">
					{{ error }}
				</div>
				{% endfor %}
			{% else %}
				{% include "wingwoo/field_pattern.html" with class="is-valid" field=field %}
			{% endif %}
		{% else %}
			{% include "wingwoo/field_pattern.html" with class="" field=field %}
		{% endif %}
		</div>
			{% if field.help_text %}
			{% autoescape off %}
			<span class="help-block">{{ field.help_text }}</span>
			{% endautoescape %}
		{% endif %}
	{% endwith %}
</div>
{% endblock %}

{% block addons %}
<div class='real-form-group'>
	<label>Add-ons:</label>
	<div>
		{% render_field form.waterproof %}<label class="checkbox-inline" for="id_waterproof">Waterproof &nbsp</label>
		{% render_field form.underlay %}<label class="checkbox-inline" for="id_underlay">Underlay &nbsp</label>
		{% render_field form.edge %}<label class="checkbox-inline" for="id_edge">Edge &nbsp</label>
	</div>
</div>
{% endblock %}

wingwoo/templates/forms/GeneralPurchaseOrder.html
{% extends 'forms/PurchaseOrder.html' %}

{% block colorpattern %}
<div class="real-form-group">
	{% with field=form.color %}
		{{ field.label_tag }}
		<div class="form-inline">
		{% if form.is_bound %}
		  	{% if field.errors %}
		  		{% include "wingwoo/field_color.html" with class="form-control is-invalid" field=field %}
		    	{% for error in field.errors %}
				<div class="invalid-feedback">
					{{ error }}
				</div>
		    	{% endfor %}
		    {% else %}
				{% include "wingwoo/field_color.html" with class="is-valid" field=field %}
			{% endif %}
		{% else %}
			{% include "wingwoo/field_color.html" with class="" field=field %}
		{% endif %}
		</div>

		{% if field.help_text %}
			{% autoescape off %}
			<span class="help-block">{{ field.help_text }}</span>
			{% endautoescape %}
		{% endif %}
	{% endwith %}
</div>
{% endblock %}

wingwoo/templates/forms/PurchaseOrder.html
{% load staticfiles %}
<!--//End-header-->
<form id="purchase-form" name="purchase-form" class="add-to-cart-form" method="post" enctype="multipart/form-data" action="{{ purchaseurl }}">
    {% csrf_token %}
    {% load widget_tweaks %}

	{% if form.non_field_errors %}
		<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{ error }}
		{% endfor %}
		</div>
	{% endif %}

	<input type="hidden" name="product_id" value="{{ product_id }}">

	{% render_field form.member class="form-control" %}
	<div>
		{% include 'forms/field_size.html' with field_length=form.length field_width=form.width field_height=form.height field_known_size=form.known_size %}



		<div class="real-form-group">
			{% with field=form.quantity %}
				{{ field.label_tag }}
				<div class="form-inline">
				{% if form.is_bound %}
				  	{% if field.errors %}
				    	{% render_field field class="form-control is-invalid" %}
				    	{% for error in field.errors %}
						<div class="invalid-feedback">
							{{ error }}
						</div>
				    	{% endfor %}
					{% else %}
						{% render_field field class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% render_field field class="form-control" %}
				{% endif %}
				</div>

				{% if field.help_text %}
					{% autoescape off %}
					<span class="help-block">{{ field.help_text }}</span>
					{% endautoescape %}
				{% endif %}
			{% endwith %}
		</div>
		
		{% block colorpattern %}
		{% endblock %}

		{% block addons %}
		{% endblock %}

		<div id="price-detail">
			<label >Price:</label>
			<label id="purchaseprice">waiting for product information</label>
		</div>
	</div>

	<div class='form-footer'>
		{% include 'forms/field_boat.html' with field=form.boat is_authenticated=is_authenticated %}
		{% include 'forms/add_to_cart_button.html' with is_authenticated=is_authenticated %}
	</div>
</form>

wingwoo/templates/forms/RepairOrder.html
{% load staticfiles %}
<!--//End-header-->
<form id="repair-form" name="repair-form" class="add-to-cart-form" method="post" enctype="multipart/form-data" action="{{ repairurl }}">
    {% csrf_token %}
    {% load widget_tweaks %}

	{% if form.non_field_errors %}
		<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{ error }}
		{% endfor %}
		</div>
	{% endif %}


	{% render_field form.member class="form-control" %}

	<div>
		<div class="real-form-group">
			{% with field=form.image %}
				{{ field.label_tag }}
				<div class="form-inline">
				{% if form.is_bound %}{% if field.errors %}
						{% include 'forms/input_image.html' with class="form-control is-invalid" %}
				    	{% for error in field.errors %}
						<div class="invalid-feedback">
							{{ error }}
						</div>
				    	{% endfor %}
					{% else %}
						{% include 'forms/input_image.html' with class="form-control is-valid" %}
					{% endif %}
				{% else %}
					{% include 'forms/input_image.html' with class="form-control" %}
				{% endif %}
				</div>

				{% if field.help_text %}
					{% autoescape off %}
					<span class="help-block">{{ field.help_text }}</span>
					{% endautoescape %}
				{% endif %}
			{% endwith %}
		</div>

		{% include 'forms/field_size.html' with field_length=form.length field_width=form.width field_height=form.height field_known_size=form.known_size %}

		<div id="price-detail">
			<label id="repairprice" style="color: red;">Notice: Price will be quoted by Wing Woo</label>
		</div>
	</div>
	<div class='form-footer'>
		{% include 'forms/field_boat.html' with field=form.boat is_authenticated=is_authenticated %}
		{% include 'forms/add_to_cart_button.html' with is_authenticated=is_authenticated %}
    </div>
</form>


wingwoo/templates/forms/add_to_cart_button.html
<button type="submit" class="btn btn-primary btn-success add-to-cart" 
	{% if is_authenticated == False %}
		data-toggle="tooltip" data-placement="right" title="Login required" disabled
	{% endif %}
>Add to Cart</button>

wingwoo/templates/forms/boat.html
<div class="modal fade" id="boatModal" tabindex="-1" role="dialog" aria-labelledby="boatModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="boatModalLabel">Add Boat</h4>
			</div>
			<form id="boatForm">
				<div class="modal-body" id="boatModalBody">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="button" id="button-boat" class="btn btn-primary">Add</button>
				</div>
			</form>
		</div>
	</div>
</div>

wingwoo/templates/forms/boat_form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="real-form-group-fix">
    
    {{ field.label_tag }}
    <div class="form-inline">
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
        
        {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
      <button type="button" class="btn btn-basic boatModalButton"><span class="glyphicon glyphicon-plus"></span></button>
      <button type="button" class="btn btn-primary boatEditButton"><span class="glyphicon glyphicon-pencil"></span></button>
      <button type="button" class="btn btn-danger boatRemoveButton"><span class="glyphicon glyphicon-remove"></span></button>
    {% endif %}
    </div>
    {% if field.help_text %}
      {% autoescape off %}
      <span class="help-block">{{ field.help_text }}</span>
      {% endautoescape %}
    {% endif %}
    
  </div>
{% endfor %}

wingwoo/templates/forms/editboat.html
<div class="modal fade" id="editBoatModal" tabindex="-1" role="dialog" aria-labelledby="editBoatModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="editBoatModalLabel">Edit Boat</h4>
			</div>
			<form id="editBoatForm">
				<div class="modal-body" id="editBoatModalBody">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<button type="button" id="button-edit-boat" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>

wingwoo/templates/forms/field_boat.html
{% load widget_tweaks %}

<div class="real-form-group">
	{{ field.label_tag }}
	<div class="form-inline">
	{% if form.is_bound %}
		{% if field.errors %}
			{% render_field field class="form-control is-invalid" %}
			{% for error in field.errors %}
			<div class="invalid-feedback">
				{{ error }}
			</div>
			{% endfor %}
		{% else %}
			{% render_field field class="form-control is-valid" %}
		{% endif %}
	{% else %}
		{% render_field field class="form-control" %}
		<button type="button" class="btn btn-primary boatModalButton" {% if is_authenticated == False %}disabled{% endif %}>Add Boat</button>
	{% endif %}
	</div>

	{% if field.help_text %}
		{% autoescape off %}
		<span class="help-block">{{ field.help_text }}</span>
		{% endautoescape %}
	{% endif %}
</div>

wingwoo/templates/forms/form_base.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="real-form-group">
    
    {{ field.label_tag }}
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
      
    {% endif %}
    </div>
    {% if field.help_text %}
      {% autoescape off %}
      <span class="help-block">{{ field.help_text }}</span>
      {% endautoescape %}
    {% endif %}
    
  </div>
{% endfor %}

wingwoo/templates/forms/input_image.html
<input type="file" name="image" class="{{class}}" id="id_image">